/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package K_Form;

import K_Classes.Functions;
import K_Classes.Paintings_class;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.border.Border;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author Justin
 */
public class Dashboard extends javax.swing.JFrame {

    
    //Border for button
    Border buttonBorder1 = BorderFactory.createMatteBorder(1, 1, 1, 1, Color.white);
    Border buttonBorder0 = BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(239,230,213));
    
    K_Classes.Functions func = new Functions();
    K_Classes.Paintings_class paints = new Paintings_class();
    //Create array for 5 pics
    JLabel[] labels_tab = new JLabel[5];
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        
        //center form
        this.setLocationRelativeTo(null);
        
        func.displayImage(jLabel1.getWidth(),jLabel1.getHeight(),null, "/K_Image/2_dashboard.png", jLabel1);
        
        
        
        
        Border panelHeaderBorder = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        Header.setBorder(panelHeaderBorder);
        
        //add border for jpanel on the left
        Border panelHeaderBorder_1 = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        j1_header.setBorder(panelHeaderBorder_1);
        
        Border panelHeaderBorder_2 = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        j2_header.setBorder(panelHeaderBorder_2);
        
        Border panelHeaderBorder_3 = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        j3_header.setBorder(panelHeaderBorder_3);
        
        Border panelHeaderBorder_4 = BorderFactory.createMatteBorder(0, 0, 1, 0, Color.white);
        jLabel6.setBorder(panelHeaderBorder_4);
        
        addBorders();
        buttonsHoverEffect();
        displayCount();
        
        //5Pics
        //First SET
        
        labels_tab[0] = jLabel_Image1;
        labels_tab[1] = jLabel_Image2;
        labels_tab[2] = jLabel_Image3;
        labels_tab[3] = jLabel_Image4;
        labels_tab[4] = jLabel_Image5;
        
        //SECOND Let's rock
        paints.displayPaintingPicture(labels_tab);
       
    }

    
        //Add for all panel
    public void addBorders()
    {
        Component[] comps=j_menu.getComponents();
         
         for(Component comp : comps)
         {
             //Check component is a button ?
             if(comp instanceof JButton)
             { 
                 JButton button =(JButton) comp;
              
                        button.setBorder(buttonBorder0);
                   
             }
        }
    }
        
        
        
    public void buttonsHoverEffect(){
         Component[] comps=j_menu.getComponents();
         
         for(Component comp : comps)
         {
             //Check component is a button ?
             if(comp instanceof JButton)
             { 
                 JButton button =(JButton) comp;
                 
                 //add action to button
                 button.addMouseListener(new MouseAdapter(){
                 
                    @Override
                    public void mouseEntered(MouseEvent evt)
                    {
                        button.setBorder(buttonBorder1);
                    }
                    @Override
                    public void mouseExited(MouseEvent evt)
                    {
                        button.setBorder(buttonBorder0);
                    }
                    
             });
         }
    }
    }
     
    //Show COUNT for LABEL
    public void displayCount(){
        
        jLabel_numPainting.setText(String.valueOf(func.countData("painting")));
        jLabel_numCust.setText(String.valueOf(func.countData("customer")));
        jLabel_numAuthor.setText(String.valueOf(func.countData("author")));
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        j_menu = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton_cust_update = new javax.swing.JButton();
        jButton_cust_del = new javax.swing.JButton();
        jButton_cust_seeAll = new javax.swing.JButton();
        jButton_cust_add = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton_man_genres = new javax.swing.JButton();
        jButton_man_author = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel_func = new javax.swing.JLabel();
        jButton_return = new javax.swing.JButton();
        jButton_paint_update = new javax.swing.JButton();
        jButton_paint_del = new javax.swing.JButton();
        jButton_paint_seeAll = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton_paint_add1 = new javax.swing.JButton();
        jButton_issue = new javax.swing.JButton();
        jButton_manageUsers = new javax.swing.JButton();
        j1 = new javax.swing.JPanel();
        j1_header = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel_numPainting = new javax.swing.JLabel();
        j2 = new javax.swing.JPanel();
        j2_header = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel_numCust = new javax.swing.JLabel();
        j3 = new javax.swing.JPanel();
        j3_header = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel_numAuthor = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel_Image1 = new javax.swing.JLabel();
        jLabel_Image2 = new javax.swing.JLabel();
        jLabel_Image3 = new javax.swing.JLabel();
        jLabel_Image4 = new javax.swing.JLabel();
        jLabel_Image5 = new javax.swing.JLabel();
        jLabel_hello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        j_menu.setBackground(new java.awt.Color(239, 230, 213));

        Header.setBackground(new java.awt.Color(157, 190, 183));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Art Gallery");

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel9.setText("Customers");

        jButton_cust_update.setText("Update");
        jButton_cust_update.setContentAreaFilled(false);
        jButton_cust_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cust_updateActionPerformed(evt);
            }
        });

        jButton_cust_del.setText("Delete");
        jButton_cust_del.setContentAreaFilled(false);
        jButton_cust_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cust_delActionPerformed(evt);
            }
        });

        jButton_cust_seeAll.setText("All Customers");
        jButton_cust_seeAll.setContentAreaFilled(false);
        jButton_cust_seeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cust_seeAllActionPerformed(evt);
            }
        });

        jButton_cust_add.setText("Add");
        jButton_cust_add.setContentAreaFilled(false);
        jButton_cust_add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_cust_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cust_addActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setText("Genres");

        jButton_man_genres.setText("Manage Genres");
        jButton_man_genres.setContentAreaFilled(false);
        jButton_man_genres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_man_genres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_man_genresActionPerformed(evt);
            }
        });

        jButton_man_author.setText("Manage Authors");
        jButton_man_author.setContentAreaFilled(false);
        jButton_man_author.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_man_author.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_man_authorActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel13.setText("Authors");

        jLabel_func.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel_func.setText("Function");

        jButton_return.setText("Return");
        jButton_return.setContentAreaFilled(false);
        jButton_return.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_returnActionPerformed(evt);
            }
        });

        jButton_paint_update.setText("Update");
        jButton_paint_update.setContentAreaFilled(false);
        jButton_paint_update.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_paint_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_paint_updateActionPerformed(evt);
            }
        });

        jButton_paint_del.setText("Delete");
        jButton_paint_del.setContentAreaFilled(false);
        jButton_paint_del.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_paint_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_paint_delActionPerformed(evt);
            }
        });

        jButton_paint_seeAll.setText("All Paintings");
        jButton_paint_seeAll.setContentAreaFilled(false);
        jButton_paint_seeAll.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_paint_seeAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_paint_seeAllActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel11.setText("Paintings");

        jButton_paint_add1.setText("Add");
        jButton_paint_add1.setContentAreaFilled(false);
        jButton_paint_add1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_paint_add1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_paint_add1ActionPerformed(evt);
            }
        });

        jButton_issue.setText("Issue");
        jButton_issue.setContentAreaFilled(false);
        jButton_issue.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_issueActionPerformed(evt);
            }
        });

        jButton_manageUsers.setText("Manage Users");
        jButton_manageUsers.setContentAreaFilled(false);
        jButton_manageUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_manageUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_manageUsersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout j_menuLayout = new javax.swing.GroupLayout(j_menu);
        j_menu.setLayout(j_menuLayout);
        j_menuLayout.setHorizontalGroup(
            j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(j_menuLayout.createSequentialGroup()
                .addGroup(j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton_man_author, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(j_menuLayout.createSequentialGroup()
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(96, 96, 96))
                        .addComponent(jButton_cust_add, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_cust_seeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_cust_del, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_cust_update, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_man_genres, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_paint_seeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_paint_del, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_paint_update, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton_paint_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_manageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(j_menuLayout.createSequentialGroup()
                                .addComponent(jButton_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_return, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(j_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_func, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j_menuLayout.setVerticalGroup(
            j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j_menuLayout.createSequentialGroup()
                .addComponent(Header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_man_genres, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_man_author, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addGap(1, 1, 1)
                .addComponent(jButton_cust_add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cust_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cust_del, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_cust_seeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(jButton_paint_add1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_paint_update, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_paint_del, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_paint_seeAll, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_func)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(j_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_return, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_issue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_manageUsers)
                .addContainerGap())
        );

        j1.setBackground(new java.awt.Color(215, 234, 243));

        j1_header.setBackground(new java.awt.Color(230, 242, 248));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number Of Painting");

        javax.swing.GroupLayout j1_headerLayout = new javax.swing.GroupLayout(j1_header);
        j1_header.setLayout(j1_headerLayout);
        j1_headerLayout.setHorizontalGroup(
            j1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(93, Short.MAX_VALUE))
        );
        j1_headerLayout.setVerticalGroup(
            j1_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j1_headerLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jLabel_numPainting.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_numPainting.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_numPainting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_numPainting.setText("Author");

        javax.swing.GroupLayout j1Layout = new javax.swing.GroupLayout(j1);
        j1.setLayout(j1Layout);
        j1Layout.setHorizontalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j1_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_numPainting)
                .addGap(54, 54, 54))
        );
        j1Layout.setVerticalGroup(
            j1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j1Layout.createSequentialGroup()
                .addComponent(j1_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jLabel_numPainting)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        j2.setBackground(new java.awt.Color(119, 181, 217));
        j2.setLayout(null);

        j2_header.setBackground(new java.awt.Color(165, 206, 230));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number Of Customers");

        javax.swing.GroupLayout j2_headerLayout = new javax.swing.GroupLayout(j2_header);
        j2_header.setLayout(j2_headerLayout);
        j2_headerLayout.setHorizontalGroup(
            j2_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j2_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        j2_headerLayout.setVerticalGroup(
            j2_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j2_headerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        j2.add(j2_header);
        j2_header.setBounds(0, 0, 270, 50);

        jLabel_numCust.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_numCust.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_numCust.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_numCust.setText("Author");
        j2.add(jLabel_numCust);
        jLabel_numCust.setBounds(10, 80, 240, 50);

        j3.setBackground(new java.awt.Color(20, 57, 125));

        j3_header.setBackground(new java.awt.Color(25, 72, 159));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number Of Author");

        javax.swing.GroupLayout j3_headerLayout = new javax.swing.GroupLayout(j3_header);
        j3_header.setLayout(j3_headerLayout);
        j3_headerLayout.setHorizontalGroup(
            j3_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        j3_headerLayout.setVerticalGroup(
            j3_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, j3_headerLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jLabel_numAuthor.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel_numAuthor.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_numAuthor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_numAuthor.setText("Author");

        javax.swing.GroupLayout j3Layout = new javax.swing.GroupLayout(j3);
        j3.setLayout(j3Layout);
        j3Layout.setHorizontalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j3_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel_numAuthor, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );
        j3Layout.setVerticalGroup(
            j3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(j3Layout.createSequentialGroup()
                .addComponent(j3_header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel_numAuthor)
                .addGap(0, 38, Short.MAX_VALUE))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("OUR LATEST WONDERFUL PAINTINGS FROM MUCH TALENTS");

        jLabel_Image1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_Image1.setOpaque(true);

        jLabel_Image2.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_Image2.setOpaque(true);

        jLabel_Image3.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_Image3.setOpaque(true);

        jLabel_Image4.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_Image4.setOpaque(true);

        jLabel_Image5.setBackground(new java.awt.Color(153, 204, 255));
        jLabel_Image5.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(jLabel_Image2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Image3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Image4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_Image5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(682, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Image2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Image3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Image4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Image5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(108, Short.MAX_VALUE)
                    .addComponent(jLabel_Image1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jLabel_hello.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel_hello.setText("Hello username . Have a nice day !");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(j_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(j1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(j2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel_hello))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_hello)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(j1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(j3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_man_genresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_man_genresActionPerformed
        Genres genrForm = new Genres();
        genrForm.setVisible(true);
    }//GEN-LAST:event_jButton_man_genresActionPerformed

    private void jButton_man_authorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_man_authorActionPerformed
        Author authrForm = new Author();
        authrForm.setVisible(true);
    }//GEN-LAST:event_jButton_man_authorActionPerformed

    private void jButton_cust_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cust_addActionPerformed
        AddCustomer addCustForm = new AddCustomer();
        addCustForm.setVisible(true);
    }//GEN-LAST:event_jButton_cust_addActionPerformed

    private void jButton_cust_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cust_updateActionPerformed
        EditCustomer editCustForm = new EditCustomer();
        editCustForm.setVisible(true);
    }//GEN-LAST:event_jButton_cust_updateActionPerformed

    private void jButton_cust_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cust_delActionPerformed
        DeleteCustomer delCustForm = new DeleteCustomer();
        delCustForm.setVisible(true);
    }//GEN-LAST:event_jButton_cust_delActionPerformed

    private void jButton_cust_seeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cust_seeAllActionPerformed
        ListCustomer listCustForm = new ListCustomer();
        listCustForm.setVisible(true);
    }//GEN-LAST:event_jButton_cust_seeAllActionPerformed

    private void jButton_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_returnActionPerformed
        ReturnPainting retuPaintF = new ReturnPainting();
        retuPaintF.setVisible(true);
    }//GEN-LAST:event_jButton_returnActionPerformed

    private void jButton_paint_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_paint_updateActionPerformed
        EditPainting editPaintForm = new EditPainting();
        editPaintForm.setVisible(true);
    }//GEN-LAST:event_jButton_paint_updateActionPerformed

    private void jButton_paint_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_paint_delActionPerformed
        DeletePainting delPaintForm = new DeletePainting();
        delPaintForm.setVisible(true);
    }//GEN-LAST:event_jButton_paint_delActionPerformed

    private void jButton_paint_seeAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_paint_seeAllActionPerformed
        ListPainting listPaintForm = new ListPainting();
        listPaintForm.setVisible(true);
    }//GEN-LAST:event_jButton_paint_seeAllActionPerformed

    private void jButton_paint_add1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_paint_add1ActionPerformed
        AddPainting addPaintF = new AddPainting();
        addPaintF.setVisible(true);
    }//GEN-LAST:event_jButton_paint_add1ActionPerformed

    private void jButton_issueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_issueActionPerformed
        IssuePainting issPaintF = new IssuePainting();
        issPaintF.setVisible(true);
    }//GEN-LAST:event_jButton_issueActionPerformed

    private void jButton_manageUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_manageUsersActionPerformed
        User uForm = new User();
        uForm.setVisible(true);
    }//GEN-LAST:event_jButton_manageUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Header;
    private javax.swing.JPanel j1;
    private javax.swing.JPanel j1_header;
    private javax.swing.JPanel j2;
    private javax.swing.JPanel j2_header;
    private javax.swing.JPanel j3;
    private javax.swing.JPanel j3_header;
    private javax.swing.JButton jButton_cust_add;
    private javax.swing.JButton jButton_cust_del;
    private javax.swing.JButton jButton_cust_seeAll;
    private javax.swing.JButton jButton_cust_update;
    public javax.swing.JButton jButton_issue;
    private javax.swing.JButton jButton_man_author;
    private javax.swing.JButton jButton_man_genres;
    public javax.swing.JButton jButton_manageUsers;
    private javax.swing.JButton jButton_paint_add1;
    private javax.swing.JButton jButton_paint_del;
    private javax.swing.JButton jButton_paint_seeAll;
    private javax.swing.JButton jButton_paint_update;
    public javax.swing.JButton jButton_return;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Image1;
    private javax.swing.JLabel jLabel_Image2;
    private javax.swing.JLabel jLabel_Image3;
    private javax.swing.JLabel jLabel_Image4;
    private javax.swing.JLabel jLabel_Image5;
    public javax.swing.JLabel jLabel_func;
    public javax.swing.JLabel jLabel_hello;
    private javax.swing.JLabel jLabel_numAuthor;
    private javax.swing.JLabel jLabel_numCust;
    private javax.swing.JLabel jLabel_numPainting;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel j_menu;
    // End of variables declaration//GEN-END:variables
}
