/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package K_Form;

import java.sql.ResultSet;
import K_Classes.Customer;
import K_Classes.Functions;
import K_Classes.Paintings_class;
import java.awt.Color;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
//import java.sql.Date;
import java.util.Date;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
//import java.util.Date;
/**
 *
 * @author Justin
 */
public class ReturnPainting extends javax.swing.JFrame {

    /**
     * Creates new form ListCustomer
     */
    
    K_Classes.Customer customer = new K_Classes.Customer();
    K_Classes.Functions func = new Functions();
    K_Classes.Paintings_class painting = new K_Classes.Paintings_class();
    K_Classes.Issue_Painting issue = new K_Classes.Issue_Painting();
    
    boolean painting_Exist = false;
    boolean customer_Exist = false;
   //Hieu
    
    public ReturnPainting() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //Display Img
       // K_Classes.Functions func = new Functions();
        func.displayImage(70 , 70,null, "/K_Image/ipic2.jpg", jLabel1_header);
        
        
        //Border around the form
        Border panelHeaderBorder = BorderFactory.createMatteBorder(3, 3, 3, 3, new Color(108, 122, 137));
        jPanel1.setBorder(panelHeaderBorder);

        //Hieu
        
        //Show Customer in jTable
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1_header = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_PaintingName_ = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton_Issue = new javax.swing.JButton();
        jButton_searchPainting = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel_CustomerFullName_ = new javax.swing.JLabel();
        jButton_searchCustomer = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel_Available = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jDateChooser_IssueDate = new com.toedter.calendar.JDateChooser();
        jDateChooser_ReturnDate = new com.toedter.calendar.JDateChooser();
        jSpinner_PaintingID = new javax.swing.JSpinner();
        jSpinner_CustomerID = new javax.swing.JSpinner();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Note = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1_header.setBackground(new java.awt.Color(108, 122, 137));
        jLabel1_header.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1_header.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1_header.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1_header.setText("Issue Painting");
        jLabel1_header.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(108, 122, 137));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel_PaintingName_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_PaintingName_.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_PaintingName_.setText("Painting Name");
        jLabel_PaintingName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_PaintingName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PaintingName_MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_PaintingName_MouseEntered(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Issue Date:");

        jButton_Issue.setText("Issue");
        jButton_Issue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IssueActionPerformed(evt);
            }
        });

        jButton_searchPainting.setText("search painting");
        jButton_searchPainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchPaintingActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Enter Painting ID:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Enter Customer ID:");

        jLabel_CustomerFullName_.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_CustomerFullName_.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_CustomerFullName_.setText("Customer Full-Name");
        jLabel_CustomerFullName_.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_CustomerFullName_.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CustomerFullName_MouseClicked(evt);
            }
        });

        jButton_searchCustomer.setText("search customer");
        jButton_searchCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchCustomerActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel25.setText("Is This Painting Available:");

        jLabel_Available.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel_Available.setForeground(new java.awt.Color(0, 0, 255));
        jLabel_Available.setText("Yes-or-No");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Return Date:");

        jSpinner_PaintingID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jSpinner_CustomerID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Note:");

        jTextArea_Note.setColumns(20);
        jTextArea_Note.setRows(5);
        jScrollPane1.setViewportView(jTextArea_Note);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1_header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(79, 79, 79))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel23)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinner_PaintingID, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_searchPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_PaintingName_)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane1)
                                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSpinner_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_searchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel_CustomerFullName_)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Issue, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel_Available))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel21)
                                        .addComponent(jLabel20)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1_header, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSpinner_PaintingID)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton_searchPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_PaintingName_)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_searchCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24)
                    .addComponent(jSpinner_CustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_CustomerFullName_)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel_Available))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jDateChooser_IssueDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jDateChooser_ReturnDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Issue, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       // jText_PaintingID.setText("");
       /* jText_author.setText("");
        jText_description.setText("");
        jText_name.setText("");
        jText_price.setText("");
        jDateChooser1.setDate(new java.util.Date());0
        jSpinner_qty.setValue(0);

        jLabel22.setText("ID");
        jComboBox_genre.setSelectedIndex(0);

        jLabel_Image.setIcon(null);
        jLabel_ImagePath.setText("Path");*/

    }//GEN-LAST:event_jButton4ActionPerformed

    //This button is for show AuthorList.java
    //Hieu
    private void jButton_searchPaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchPaintingActionPerformed
            //get the paint id
            int painting_id = (int)jSpinner_PaintingID.getValue();
        
        try {
           //get the paint by id
            K_Classes.Paintings_class selectedPainting = painting.getPaintbyId(painting_id);
            //if paint exsit
            if(selectedPainting != null)
            {
                //display paint title/name
                jLabel_PaintingName_.setText(selectedPainting.getName());  
                //set the painting exist to true
                painting_Exist = true;
                
                // display avaibility
                if(issue.checkPaintingAvailability(painting_id))
                {
                    jLabel_Available.setText("YES");
                    jLabel_Available.setForeground(Color.green);
                }
                else
                {
                    jLabel_Available.setText("NO");
                    jLabel_Available.setForeground(Color.red);
                }
            }
             //if this paint doesnt exsit
            else
            {
                JOptionPane.showMessageDialog(null, "This painting doesn't exist!", "Painting Not Found", 2);
                jLabel_PaintingName_.setText("Painting Name");
                painting_Exist = false;
                jLabel_Available.setText("YES-or-NO");
                jLabel_Available.setForeground(new Color (0,0,255));
                painting_Exist = false;
                customer_Exist = false;
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(ReturnPainting.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_jButton_searchPaintingActionPerformed

    private void jButton_IssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IssueActionPerformed
        //Hieu
        int _painting_id = (int)jSpinner_PaintingID.getValue();
        int _customer_id = (int)jSpinner_CustomerID.getValue();
        String _note = jTextArea_Note.getText();
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try
        {
            String _issue_date = dateFormat.format(jDateChooser_IssueDate.getDate());
            String _return_date = dateFormat.format(jDateChooser_ReturnDate.getDate());
            
            Date issDate = dateFormat.parse(_issue_date);
            Date rtnDate = dateFormat.parse(_return_date);
            
            if(!painting_Exist) //if paint doesn't exist
            {
                JOptionPane.showMessageDialog(null, "You Need To Check If This Painting Exist First By Clicking The Search Painting Button ", "Check If The Painting Exist", 2);
            }
            else if(!customer_Exist) //if customer doesn't exist
            {
                 JOptionPane.showMessageDialog(null, "You Need To Check If This Customer Exist First By Clicking The Search Customer Button ", "Check If The Customer Exist", 2);
            }
            else if(!issue.checkPaintingAvailability(_painting_id))
            {
                JOptionPane.showMessageDialog(null, "This Painting Is Not Available Right Now!", "Painting Is Not Available", 2);
            }
            
            else if(rtnDate.before(issDate)) //if return day happen befoer issue day
            {
                JOptionPane.showMessageDialog(null, "The Return Date Must Be After The Issue Date", "Wrong Return Date", 2);
            }
            else
            {
                 issue.addIssue(_painting_id, _customer_id, "issued", _issue_date, _return_date, _note);
                 //reset fields
                 jSpinner_PaintingID.setValue(0);
                 jSpinner_CustomerID.setValue(0);
                 jLabel_PaintingName_.setText("Painting Name");
                 jLabel_CustomerFullName_.setText("Customer Full-Name");
                 jDateChooser_IssueDate.setDate(new Date());
                 jDateChooser_ReturnDate.setDate(new Date());
                 
                 jLabel_Available.setText("YES-or-NO");
                 jLabel_Available.setForeground(new Color (0,0,255));
            }
           
        }
        catch (HeadlessException | NullPointerException | ParseException ex) 
        {
            JOptionPane.showMessageDialog(null, "Select Issue Date & Return Date", "Select Date", 2);
        }
        
    }//GEN-LAST:event_jButton_IssueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton_searchCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchCustomerActionPerformed
        // search and display customer
              //get the customer id
            int customer_id = (int)jSpinner_CustomerID.getValue();
        
        try {
           //get the customer by id
            K_Classes.Customer selectedCustomer = customer.getCustomerbyId(customer_id);
            //if paint exsit
            if(selectedCustomer != null)
            {
                //display member name
                jLabel_CustomerFullName_.setText(selectedCustomer.getFirstName() + " " + selectedCustomer.getLastName());  
                //set the customer exist to true
                customer_Exist = true;
            }
             //if this customer doesnt exsit
            else
            {
                JOptionPane.showMessageDialog(null, "This customer doesn't exist!", "Customer Not Found", 2);
                jLabel_CustomerFullName_.setText("Customer Full-Name");
                customer_Exist = false;
            }
                    
        } catch (SQLException ex) {
            Logger.getLogger(ReturnPainting.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_jButton_searchCustomerActionPerformed

    private void jLabel_PaintingName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PaintingName_MouseClicked
        // display paint info card
        int painting_id = (int)jSpinner_PaintingID.getValue();
        PaintingInfoCardForm paintingCardF = new PaintingInfoCardForm(painting_id);
      
        paintingCardF.setVisible(true);
    }//GEN-LAST:event_jLabel_PaintingName_MouseClicked

    private void jLabel_CustomerFullName_MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CustomerFullName_MouseClicked
        //// display customer info card
        int customer_id = (int)jSpinner_CustomerID.getValue();
        CustomerInfoCardForm customerCardF = new CustomerInfoCardForm(customer_id);
        customerCardF.setVisible(true);
    }//GEN-LAST:event_jLabel_CustomerFullName_MouseClicked

    private void jLabel_PaintingName_MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PaintingName_MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel_PaintingName_MouseEntered

     
    
    
    
    //Method-Function
    
   
   
    public boolean verif()
    {
        //Hieu  
        return true;
    }
    
    //Hieu
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnPainting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnPainting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton_Issue;
    private javax.swing.JButton jButton_searchCustomer;
    private javax.swing.JButton jButton_searchPainting;
    private com.toedter.calendar.JDateChooser jDateChooser_IssueDate;
    private com.toedter.calendar.JDateChooser jDateChooser_ReturnDate;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel1_header;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel_Available;
    private javax.swing.JLabel jLabel_CustomerFullName_;
    private javax.swing.JLabel jLabel_PaintingName_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner_CustomerID;
    private javax.swing.JSpinner jSpinner_PaintingID;
    private javax.swing.JTextArea jTextArea_Note;
    // End of variables declaration//GEN-END:variables
}
